### ISSUE TITLE
Dropdown Nav Dynamically Accessible (Remove JS)

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/brand-patterns#1]
The idea is to try and remove the Javascript part of that makes the dropdown nav and it's accessible features. Will need to test this feature out before talking to Nathan about including the accessible features with r:site_menu radius tag. Will also need to create a CSS version of the dropdown menu which will make loading the pattern easier and help with overall site performance.

**Comment by adamjohnson** [comment]
Two resources:

http://examples.simplyaccessible.com/css-menu/option-4.html

From that, I made the quicklinks menu from Slate:

http://slatecms.wvu.edu/howtos/developers/theme_development/quicklinks_drop_down_menu

It's CSS based and progressively enhanced via JS. The only drawback is the jQuery dependency. I'm sure someone here could figure out how to change that to vanilla JS.

**Comment by adamjohnson** [comment]
This is resolved via 037d063f2a8a59ed1b9ca06a9225400a091c0596, 096bee95380706ec2f2d478837d9264db6a06752, 7bb0f85a11bfcce06191d13902d5653f9dc9aa91 and fd4df91653ac440d261106ca1088cdc3e16593b2.
