### ISSUE TITLE
Fieldset/Form issue on patterns.wvu.edu

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/brand-patterns#15]
Even though there isn't really a pattern for a form, I figure the code might be copied moving forward I wanted go ahead and note this here as an issue.   

On [http://patterns.wvu.edu/example-back-page](http://patterns.wvu.edu/example-back-page) under Fieldsets and Forms the `<fieldset>` should be inside of the `<form>` tag.

Also, this more then likely needs a separate issue but it is of my opinion that it may be better to wrap form elements in to `<div>` tags instead of `<p>` tags?  That way you don't have to override typography styles to adjust form styles.  But then again, because this isn't a direct "pattern" may be a moot point.

I see that [Bitters](http://bitters.bourbon.io/example.html#form_elements) does use the `<p>` tags.

[Bootstrap](http://getbootstrap.com/css/#forms) obviously uses `<div>` tags.

Thoughts?

**Comment by adamglenn** [comment]
The only reason they are <p> tags is because I stole them from Bitters. They aren't really paragraphs though, so I will switch to <div>s.

**Comment by zeroedin** [comment]
@dustinmazon @adamjohnson comments?

**Comment by adamjohnson** [comment]
I'd follow what bootstrap does in the way of forms. They've got that shi# on lock.

**Comment by adamglenn** [comment]
I'm going to close this. I moved the fieldset inside the form and removed <p> tags. That is in Adam G's Magic Pattern Library theme though. I created a separate issue to replace the Bitters form stuff with Boostrap for the brand-patterns theme.
