### ISSUE TITLE
Namespace CSS

### ISSUE THREAD

**Issue by joshrcook** [wvuweb/brand-patterns#19]
My workflow is usually to build a site out in HTML, and then go back and hook in the CMS and bring everything together.  I'm having some problems, though, because the base CSS from the patterns project is messing up the CSS that I've built for the site.  Yes, I could go back and redo the CSS, but I'd rather not have to do that with every project.  It would be really nice if the CSS was constrained using a namespace.  For a good example, UIKit (http://getuikit.com/) does this really well, and nicely integrates with existing code.

Thanks!  By the way, if you want me to help work on this, I can.  You'll probably want to think about the approach you want to take some more though.

**Comment by dmolsen** [comment]
@joshrcook -

Could you provide some examples of where you're seeing your styles get messed up? e.g. elements or class names. Looking through the project the vast majority of it is name spaced. Obviously for certain elements, especially type, we want to enforce brand styling regardless. Adding a name-spaced class to every `h2` on a web page seems counter-productive.

Trying to backfill with the brand styles is just going to cause pain. Maybe with future projects you can start with the brand styles and views as a base and override from there? The entire point of this project is to act as a bootstrap for the brand and Clean Slate websites. Brand shouldn't really be thought of as a "tack-on." And, I can't stress this enough, this is about **brand** which puts in a slightly different class than UIKit.

**Comment by joshrcook** [comment]
Fair enough.  It probably makes sense to start with the brand patterns base CSS then.

I guess I was confused on the purpose of the brand patterns project.  I thought that the Cleanslate Toolkit was the starter CSS, and the brand patterns project was just a collection of plugin-type partials that would be namespaced into modules to plug into a site.  So I guess that's where the namespace request came from.

Thanks!
