### ISSUE TITLE
Change paths to use HTTPS

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/brand-patterns#20]
All of the paths for the following resources should be `https` instead of `http` or `//`:

https://github.com/wvuweb/brand-patterns/blob/master/scss/1-base/_wvu-variables.scss#L39
https://github.com/wvuweb/brand-patterns/blob/master/scss/1-base/_wvu-variables.scss#L54-L70

https://github.com/wvuweb/brand-patterns/blob/master/views/layouts/default.html#L9
https://github.com/wvuweb/brand-patterns/blob/master/views/layouts/default.html#L39-L40
https://github.com/wvuweb/brand-patterns/blob/master/views/layouts/default.html#L53-L54

Also, any references to `cal.wvu.edu` should use HTTPS.

More info on making HTTPS work in my blog post:

https://cleanslatecms.wvu.edu/blog/2015/04/23/cleanslate-moving-to-https

**Comment by adamjohnson** [comment]
Looks like there's much more here referencing `http` than I outlined above. Do a Find In Files (CMD + Shift + F in Sublime Text) and search your project for `http` to find all the resources (mostly images it looks like) to change to `https`.

**Comment by zeroedin** [comment]
We should also consider moving those static assets to static.wvu.edu.

**Comment by adamjohnson** [comment]
Why move those assets to static in lieu of this: http://cleanslatecms.wvu.edu/blog/2015/03/30/improving-caching ?

**Comment by zeroedin** [comment]
I would say because they are globally shared assets that are used across many themes.  They are unlikely to change unless the pattern themselves change.  Kinda the definition of the static asset global shared repo/project.  I'm sure opinions vary.
