### ISSUE TITLE
Touch controls in mobile

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/brand-patterns#3]
While using the drop down in mobile, once expanded, it seems like the actual tags are moving with the screen, even though the visual elements arent. This is in iOS 7.1.2 on the iPhone 5 base model - iOS 8.0.2 on the iPhone 6 base model.

![Image of Menu](http://i.imgur.com/QDezyMr.jpg)

**Comment by adamglenn** [comment]
@zeroedin @dustinmazon @adamjohnson Can anyone else replicate this problem? It is not happening for me.

**Comment by adamjohnson** [comment]
Could not reproduce this via the iOS simulator with iPhone 6 and iOS 8.0.3.

**Comment by zeroedin** [comment]
What is a url I can test on?

**Comment by adamglenn** [comment]
Checking with Jason. Assuming it was something from the patterns site e.g. http://patterns.wvu.edu/example-landing-page but will wait to hear back.

**Comment by adamjohnson** [comment]
Since we haven't heard anything more on this issue, I'm going to go ahead and close it. @jmarkle825 chime in if you feel differently.

**Comment by jmarkle825** [comment]
@adamglenn @adamjohnson @zeroedin Not sure how I missed the notification on this. The issue was resolved a while ago. Sorry about that!
