### ISSUE TITLE
Add staff/directory listing pattern from Career Services theme

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/brand-patterns#32]

**Comment by adamjohnson** [comment]
Honors college does this:

https://stash.development.wvu.edu/projects/CST/repos/honors-college/browse/views/profile_index.html

http://honors.wvu.edu/profiles

So does Diversity, only they break it down by department. So, Diversity > Department > Profile. Each department has their own unique URL with their staff listing:

https://stash.development.wvu.edu/projects/CST/repos/diversity/browse/views/staff_index.html

http://diversity.wvu.edu/ddei/about-the-division/staff

**Comment by adamjohnson** [comment]
This has been documented on the patterns site:

https://patterns.wvu.edu/patterns#wvu-profile-page-examples

Now available as a new pattern and serves as a great example of how to pull content from one page onto another.
