### ISSUE TITLE
Add support for rvm

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/brand-patterns#6]
Add a `.ruby-version` and `.ruby-gemset` file to the root.

**Comment by adamjohnson** [comment]
:+1:. These can be found here if you need them:

https://stash.development.wvu.edu/projects/CST/repos/admissions-orientation-v2/browse

**Comment by zeroedin** [comment]
This is now a moot point that node-sass upgraded to version 2.0.1.  The .ruby-version and .ruby-gemset files have been removed:  References @a2478313
