### ISSUE TITLE
Add Gemfile

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/brand-patterns#7]
Add a Gemfile so you can lock to a certain version of tested sass.

```Ruby
source 'https://rubygems.org'

gem 'sass', '~> 3.4.13'
```

**Comment by adamjohnson** [comment]
:+1:

**Comment by zeroedin** [comment]
This is now a moot point that node-sass upgraded to version 2.0.1.  The Gemfile has been removed.

References @098cefb0
