### ISSUE TITLE
Quicklinks SCSS

### ISSUE THREAD

**Issue by osteffich** [wvuweb/brand-patterns#72]
I've tried to implement the Quicklinks brand pattern and come across an error. 

I made sure to include the recommended "@import 'wvu-quicklinks--flex';" on the modules-dir.scss file but am still getting a result that looks like the attached. 

Should another SCSS file be referenced somewhere? 

![image](https://cloud.githubusercontent.com/assets/1418011/20985912/72fb72ae-bc94-11e6-889d-5b69cab89d32.png)

**Comment by adamglenn** [comment]
What site is this happening on? Can you give me a link?

**Comment by osteffich** [comment]
I am still developing and found it in hammer - but I committed so you can
see it here: http://ifs.sandbox.wvu.edu/home
The quicklinks are right above the social media bar near the footer.

**Comment by adamglenn** [comment]
You need to include the wvu-quicklinks.scss file in your layouts-dir and modules-dir files. Looks like that is not in the documentation. Will fix.

**Comment by osteffich** [comment]
I just added @import 'wvu-quicklinks'; to the layouts-dir file, and it adds
some margin to the left and right, but doesn't add enough padding to make
it look like the example. The background color is still also not there.

I'll wait till tomorrow to revisit this.

**Comment by osteffich** [comment]
Ok - also added wvu-quicklinks.scss to the modules file along with the
wvu-quicklinks--flex.scss. Fixed it! Thank you.

**Comment by adamglenn** [comment]
Documentation has been updated. Not sure how that went unnoticed for so long.
